<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-B9T8IP8" ignored="0" name="Demo_Chrome" tests="2" failures="1" timestamp="2021-05-19T19:58:21 ICT" time="16.293" errors="0">
  <testcase name="login_Standard" time="9.998" classname="ExercisemvnTestcase.Testcase_login"/>
  <testcase name="login_failure" time="3.221" classname="ExercisemvnTestcase.Testcase_login">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Sorry, this user has been locked out..] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Sorry, this user has been locked out..] but found [Epic sadface: Sorry, this user has been locked out.]
at ExerciseBaseCommon.BaseActions.sAssertEqual(BaseActions.java:62)
at ExercisemvnTestcase.Testcase_login.login_failure(Testcase_login.java:44)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login_failure -->
</testsuite> <!-- Demo_Chrome -->
